### ISSUE TITLE
Discord 

### ISSUE THREAD

**Issue by 77bhgf78** [COMBINE-lab/perplexity-paper#1]
YOu guys kicked me out of your discord server for no reason at all

**Comment by rob-p** [comment]
I think you may have this confused with another project.  This repo is for the paper ["Perplexity: evaluating transcript abundance estimation in the absence of ground truth"](https://almob.biomedcentral.com/articles/10.1186/s13015-022-00214-y).  We don't have a discord server associated with this repository.
